### PR TITLE
Publish mdv as a .NET tool, for easier install

### PR DESCRIPTION
**Pull request by davidwengier**
Hopefully changing to .NET 6 isn't an issue 🤷‍♂️

### CODE REVIEW

**Comment by tmat** [comment]
Nice! Thanks! Next we should improve the command line arg parsing, use standard dotnet arg parser.

**Comment by RikkiGibson** [comment]
Thank you for this @davidwengier. I was never thrilled by rooting around my downloads folder for the manually downloaded nuget package, or digging through my nuget cache, to find mdv.exe. :P

**Comment by davidwengier** [comment]
> I was never thrilled by rooting around my downloads folder 

Funnily enough, I didn't even realise the exe was published to nuget, and I just always built locally and rooted around my artifacts folder.

> Next we should improve the command line arg parsing

I was thinking a `watch` mode, where it can monitor the `Microsoft_CodeAnalysis_EditAndContinue_LogDir` folder and run automatically every time a new generation is added.. though a new env var to tell roslyn to run `mdv` after it outputs those logs would work too.

**Comment by tmat** [comment]
I meant removing the custom command line parsing impl.

> I was thinking a watch mode, where it can monitor the Microsoft_CodeAnalysis_EditAndContinue_LogDir folder and run automatically every time a new generation is added

Maybe, but not sure how much it's actually useful. One generation is usually enough for repro diagnosis.

> though a new env var to tell roslyn to run mdv after it outputs those logs would work too.

It wouldn't be good to add dependency on mdv to Roslyn.

**Comment by davidwengier** [comment]
> One generation is usually enough for repro diagnosis.

I'm playing around with this again because i'm preparing for a conference talk in a couple of weeks, so I mainly want it entirely selfishly :D
Once I've delivered the talk I'm sure the want will completely vanish.

**Pull request merged**
